VersionInfo for pbr needs to be package name
This fixes a bug in which we incorrectly passed the wrong package name
to pbr.  This will fix:

  Exception: Versioning for this project requires either an sdist
  tarball, or access to an upstream git repository. Are you sure that
  git is installed?

Change-Id: Ib2e83e3fb5c6dbc7c4788e646edf667f31c505b4
Signed-off-by: Paul Belanger <pabelanger@redhat.com>